<?php
/**
 * API: Regenerate download token (self-service)
 * POST /api/customer/regenerate-download.php
 */

require_once __DIR__ . '/../../includes/config.php';
require_once __DIR__ . '/../../includes/db.php';
require_once __DIR__ . '/../../includes/customer_auth.php';
require_once __DIR__ . '/../../includes/delivery_state.php';

header('Content-Type: application/json');

$customerId = requireCustomerAuth();
if (!$customerId) {
    echo json_encode(['success' => false, 'error' => 'Authentication required']);
    exit;
}

$input = json_decode(file_get_contents('php://input'), true);
$deliveryId = (int)($input['delivery_id'] ?? 0);

if (!$deliveryId) {
    echo json_encode(['success' => false, 'error' => 'Delivery ID required']);
    exit;
}

$db = getDb();

$stmt = $db->prepare("
    SELECT d.*, po.customer_id 
    FROM deliveries d
    JOIN pending_orders po ON d.pending_order_id = po.id
    WHERE d.id = ? AND po.customer_id = ?
");
$stmt->execute([$deliveryId, $customerId]);
$delivery = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$delivery) {
    echo json_encode(['success' => false, 'error' => 'Delivery not found']);
    exit;
}

if ($delivery['product_type'] !== 'tool') {
    echo json_encode(['success' => false, 'error' => 'Only tool downloads can be regenerated']);
    exit;
}

$stmt = $db->prepare("
    SELECT COUNT(*) FROM download_token_regenerations
    WHERE delivery_id = ? AND created_at > datetime('now', '-24 hours')
");
$stmt->execute([$deliveryId]);
$regenCount = $stmt->fetchColumn();

if ($regenCount >= 5) {
    echo json_encode(['success' => false, 'error' => 'Too many regeneration requests today. Please contact support.']);
    exit;
}

require_once __DIR__ . '/../../includes/tool_files.php';

$files = getToolFiles($delivery['product_id']);
if (empty($files)) {
    echo json_encode(['success' => false, 'error' => 'No files available for download']);
    exit;
}

$downloadLinks = [];
foreach ($files as $file) {
    $link = generateDownloadLink($file['id'], $delivery['pending_order_id']);
    if ($link) {
        $downloadLinks[] = $link;
    }
}

$stmt = $db->prepare("UPDATE deliveries SET delivery_link = ? WHERE id = ?");
$stmt->execute([json_encode($downloadLinks), $deliveryId]);

$stmt = $db->prepare("
    INSERT INTO download_token_regenerations (delivery_id, customer_id, created_at)
    VALUES (?, ?, datetime('now'))
");
$stmt->execute([$deliveryId, $customerId]);

if ($delivery['delivery_state'] === 'expired') {
    markDeliveryState($deliveryId, 'ready', 'Token regenerated by customer');
}

echo json_encode([
    'success' => true,
    'message' => 'New download links generated! Valid for ' . (defined('DOWNLOAD_LINK_EXPIRY_DAYS') ? DOWNLOAD_LINK_EXPIRY_DAYS : 30) . ' days.',
    'download_links' => $downloadLinks,
    'regenerations_remaining' => 5 - $regenCount - 1
]);
